\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{graphics}
\usepackage{booktabs}
\usepackage{colortbl, xcolor}


\begin{document}

%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{signal.hsmm Benchmarks and Supplementary Materials}
%\VignetteDepends{signal.hsmm}
%\VignettePackage{signal.hsmm}

\tableofcontents


\section{Signal peptide structure}
\begin{figure}[ht]
\caption{Schematic organization of signal peptide structure.}
\centering
\scalebox{0.4}{
\includegraphics{SP.png}
}
\end{figure}

%maybe we should go with lengths calculated on our data set 0.05 quantile, 0.95 quantile
Typical signal peptide contains following regions~\cite{voss_mechanism_2013, jain_signal_1994}:
\begin{itemize}
\item n-region (5-8 residues long, mostly basic residues), 
\item h-region (8-12 residues long, strongly hydrophobic residues),
\item c-region (usually 6 residues long, few polar and uncharged residues),
\item cleavage site (a very variable protein composition, but typically at -3 and -1 positions small, neutral residuals).
\end{itemize}
%note to self: Nielsen's heuristic algorithm makes overlapping c-region and cleavage site

\section{Graphical User Interface} 

signal.hsmm can be used in batch mode as any other R package, but for convinience of users graphical user interface is also avaible. The GUI can be accessed directly on the web page
https://michbur.shinyapps.io/signalhsmm/ or from R using command: gui\_{}signal.hsmm\({}\){}. It is powered by the shiny package and uses functions accessible in signal.hsmm package. Starting GUI directly from R requires additional packages: shinyAce, markdown and knitr.

\begin{figure}[ht]
\caption{signal.hsmm gui welcome screen. Data is already pasted into submit text area.}
\label{gui2}
\centering
\scalebox{0.22}{
\includegraphics{gui2.png}
}
\end{figure}

The input data can be directly submitted by using text area in the middle of graphical user interface as well as by .txt or .fasta files (Fig.~\ref{gui2}). Due to the server capacity, the maximum number of sequences in the single query cannot exceed 300.

\begin{figure}[ht]
\caption{Job completed - "Data input" panel.}
\label{gui3}
\centering
\scalebox{0.22}{
\includegraphics{gui3.png}
}
\end{figure}

After succesfull submission and analysis, panel "Data input" contains quick summary of data: number of succesfully read sequences, number of detected signal peptides and their average length (Fig.~\ref{gui3}).

\begin{figure}[ht]
\caption{"Short output" panel.}
\label{gui4}
\centering
\scalebox{0.22}{
\includegraphics{gui4.png}
}
\end{figure}

"Short output" panel (Fig.~\ref{gui4}) contains table describing probability of signal peptide, start and end of signal peptide for each analyzed sequence. The table can be downloaded in .csv format by pressing "Download short output" button.

\begin{figure}[ht]
\caption{"Long output (with graphics)" panel.}
\label{gui5}
\centering
\scalebox{0.22}{
\includegraphics{gui5.png}
}
\end{figure}

"Long output (with graphics)" panel (Fig.~\ref{gui5}) describes detected signal peptides in more detailed way. It provides information about length and aminoacid composition of predicted n-, h-, and c-regions. This prediction can be saved both without graphics in .txt format ("Download long output (without graphics)" button) or with additional graphical representation in .html formal ("Download long output (with graphics)" button).

\clearpage

\section{Amino acid aggregation} 

<<echo = FALSE,message=FALSE,results='asis'>>=
tabAminokwasow = function(aminokwasy, nazwyGrupy, ...) {
  tab = cbind(data.frame(1:length(aminokwasy)), data.frame(sapply(aminokwasy, function(x) paste(x, collapse=", "))))
  dimnames(tab) = list(nazwyGrupy, c("Group", "Amino acids"))
  xtable(tab, align = c("r", "c", "l"), ...)
}

library(xtable)
aa5 = list('1' = c("K", "R", "H"),
           '2' = c("V","I","L","M","F","W","C"),
           '3' = c("S", "T", "N", "Q"),
           '4' = c("D","E","A","P","Y","G"))
print(tabAminokwasow(aa5, c("Positively charged", "Nonpolar and aliphatic",
                            "Polar and uncharged", "Negatively charged and nonpolar"),
                     caption = "Classification of amino acids used by signal.hsmm."))
load("pub_evaluation.RData")
@

\section{Performance measures}

\subsection{Random sub-sampling validation}

Random sub-sampling validation was repeated 1000 times. 

Total data avaible: 3816 proteins with signal peptide, 9795 proteins without a signal peptide.

Training set size: 1200 proteins with signal peptide.

Test set size: 120 proteins with signal peptide, 120 proteins without signal peptide.

Results: table~\ref{monteCarlo}.

<<echo = FALSE,message=FALSE,results='asis'>>=
dat <- data.frame(colMeans(thousand_reps_measur))
dat <- cbind(rownames(dat), dat)
rws <- seq(1, nrow(dat), by = 2)
colour <- rep("\\rowcolor[gray]{0.85}", length(rws))
colnames(dat) <- c("Performance measure", "Value")
print(xtable(dat, caption = "Mean performance measures of signal.hsmm in random sub-sampling validation.", label = "monteCarlo", align = "lcl"), include.rownames = FALSE,
      add.to.row = list(pos = as.list(rws), command = colour),
      booktabs = TRUE)
@  





\subsection{Comparision with other predictors}

\begin{table}
\begin{tabular}{ccc}
\hline
\rowcolor{white!100}
Classifier name  & Size of train data & Proteins added before year  \\ \hline
signal.hsmm-2010 & 3676               & 2010                        \\
signal.hsmm-2004 & 3086               & 2004                        \\
signal.hsmm-1997 & 2473               & 1997                        \\
signal.hsmm-1990 & 1189               & 1990                        \\
signal.hsmm-1987 & 496                & 1987                        \\    
\end{tabular}
\caption{Full table of training data sets used in training different instances of signal.hsmm.}
\label{learningSets}
\end{table}

All measures, with the exception for Matthews Correlation Coefficient, were calculated using the hmeasure package.

<<echo = FALSE,message=FALSE,results='asis'>>=
citations <- c("~\\cite{petersen_signalp_2011}",
  "~\\cite{petersen_signalp_2011}",
  "~\\cite{DyrlovBendtsen2004783}",
  "~\\cite{DyrlovBendtsen2004783}",
  "~\\cite{hiller_predisi:_2004}",
  "~\\cite{kall_combined_2004}",
  "~\\cite{bagos_combined_2010}",
  "~\\cite{reynolds_transmembrane_2008}")
comp_tab <- measures[c(1L:length(citations), 9, 13), c("AUC", "H", "MCC", 
                                                       "AUCH", "KS")]
nice_tab <- comp_tab
rownames(nice_tab)[1L:length(citations)] <- paste0(rownames(nice_tab)[1L:length(citations)], citations)
print(xtable(nice_tab[-(3:4), ], align = "rccccc", caption = "Comparison of Area Under the Curve, H-measure, Matthews Correlation Coefficient,  Area Under the Convex Hull and Kolmogorov-Smirnoff statistic for different classifiers."), 
      sanitize.rownames.function = function(x) x)
@

<<echo = FALSE,message=FALSE,results='asis'>>=
comp_tab <- measures[c(1L:length(citations), 9, 13), c("Recall", "Sens", "Spec", "Precision")]
nice_tab <- comp_tab
rownames(nice_tab)[1L:length(citations)] <- paste0(rownames(nice_tab)[1L:length(citations)], citations)
print(xtable(nice_tab[-(3:4), ], align = "rcccc", caption = "Comparison of recall, sensitivity, specificity and precision for different classifiers."), sanitize.rownames.function = function(x) x)
@


<<echo = FALSE,message=FALSE,results='asis'>>=
comp_tab <- measures[c(1L:length(citations), 9, 13), c("Gini", "MER", "MWL", "ER")]
nice_tab <- comp_tab
rownames(nice_tab)[1L:length(citations)] <- paste0(rownames(nice_tab)[1L:length(citations)], citations)
print(xtable(nice_tab[-(3:4), ], align = "rcccc", caption = "Comparison of Gini coefficient, Minimum Error Rate, Minimum cost-Weighted Error Rate and Error Rate for different classifiers."), sanitize.rownames.function = function(x) x)
@


<<echo = FALSE,message=FALSE,results='asis'>>=
comp_tab <- measures[c(1L:length(citations), 9, 13), c("TPR", "FPR", "F", "Youden")]
nice_tab <- comp_tab
rownames(nice_tab)[1L:length(citations)] <- paste0(rownames(nice_tab)[1L:length(citations)], citations)
print(xtable(nice_tab[-(3:4), ], align = "rcccc", caption = "Comparison of True Positive Rate, False Positive Rate, F-score and Youden's index for different classifiers."), sanitize.rownames.function = function(x) x)
@

<<echo = FALSE,message=FALSE,results='asis'>>=
comp_tab <- measures[c(1L:length(citations), 9, 13), c("TP", "FP", "TN", "FN")]
nice_tab <- comp_tab
rownames(nice_tab)[1L:length(citations)] <- paste0(rownames(nice_tab)[1L:length(citations)], citations)
print(xtable(nice_tab[-(3:4), ], align = "rcccc", caption = "Comparison of number of True Positives, False Positives, True Negatives and False Negatives for different classifiers."), sanitize.rownames.function = function(x) x)
@



\clearpage

\bibliographystyle{plain}
\bibliography{document}

\end{document}