#' hsmm_pred_list class
#'
#' A list of prediction(s) generated by \code{\link{run_signal.hsmm}} function.
#'
#' @details A named list. Each element belongs to the \code{\link{hsmm_pred}} class.
#' @seealso \code{\link{summary.hsmm_pred_list}} 
#' @name hsmm_pred_list
NULL

#' Summarize list of signal.hsmm predictions
#'
#' Summarizes objects of class \code{\link{hsmm_pred_list}}.
#'
#' @param object of class \code{\link{hsmm_pred_list}}.
#' @param ... ignored
#' @return Data frame of summarized informations.
#' @export
#' @keywords manip

summary.hsmm_pred_list <- function(object, ...) {
  do.call(rbind, lapply(object, function(i)
    data.frame(sp.probability = i[["sp_probability"]], 
               sp.start = i[["sp_start"]],
               sp.end = i[["sp_end"]])))
}